services:
  tailon:
    container_name: tailon
    build:
      context: .
      tags:
        - tolttech/tailon
    ports:
      - "8080:8080"
    volumes:
      - "./testdata/ex1/var/log:/tailon/logs_tailon"
      - "./tailon.toml:/tailon/tailon.toml"
    command: /tailon/logs_tailon/*
    restart: unless-stopped
