services:
  tailon:
    container_name: tailon
    build:
      context: .
      tags:
        - tolttech/tailon
    ports:
      - "8080:8080"
    volumes:
      - "/data/syslog-ng/log:/tailon/logs"
      - "./tailon.toml:/tailon/tailon.toml"
    command: /tailon/logs/messages
    restart: unless-stopped
